parameters:
- name: Stage
- name: Environment
- name: azureSubscriptionSPN
- name: location
- name: parameterFile
- name: resourcePrefix
- name: TAGEnvironment

jobs:
  - deployment: Deploy${{ parameters.Stage }}
    displayName: Deploy${{ parameters.Stage }}
    environment: ${{ parameters.Environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzurePowerShell@5
            name: GetSPNObjectId 
            inputs:
              azureSubscription: $(azureSubscriptionSPN)
              scriptType: 'InlineScript'
              inline: |
                $Context = Get-AzContext
                $AzureDevOpsServicePrincipal = Get-AzADServicePrincipal -ApplicationId $Context.Account.Id
                $ObjectId = $AzureDevOpsServicePrincipal.Id
                echo "##vso[task.setvariable variable=SPNObjectId;isOutput=true]$ObjectId"
                $GetTenantId = $Context.Tenant.Id
                echo "##vso[task.setvariable variable=tenantId;isOutput=true]$GetTenantId"
              azurePowerShellVersion: latestVersion
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: $(azureSubscriptionSPN)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group create --name s161d02-rg-OPS-core --location ${{ parameters.location }} --tags "Portfolio=Education and Skills Funding Agency" "Service Line=Data Science (CEDD)" "Service=Business Intelligence (CEDD)" "Product=Data Platform Infrastructure" "Environment=Dev" "Service Offering=ESFA Adopt Programme"
                az deployment group create  `
                --template-file main.bicep --parameters ${{ parameters.parameterFile }} --parameters  environment=${{ parameters.TAGEnvironment }} resourcegroupname='${{ parameters.resourcePrefix }}-rg-OPS-core' objectId=$(GetSPNObjectId.SPNObjectId) tenantId=$(GetSPNObjectId.tenantId) location=${{ parameters.location }} `
                --resource-group s161d02-rg-OPS-core

