name: OPS-Core-InfrastructureDeployment

parameters:
- name: Environment
  displayName: Environment
  type: string
  default: 'DevTest'
  values:
  - Dev
  - DevTest
  - Test


variables:
  - group: vg-odin-core

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DevTestRelease
    jobs:
    - template: azure-deploy.yml
      parameters:
        Stage: DevTest
        Environment: 'DevTest'
        azureSubscriptionSPN: $(devTestAzureSubscriptionSPN)
        location: $(location)
        parameterFile: $(devTestParameterFile)
        resourceGroupName: $(devTestResourceGroupName)
        TAGEnvironment: $(devTestTAGEnvironment)


  - stage: TestRelease
    jobs:
    - template: azure-deploy.yml
      parameters:
        Stage: Test
        Environment: 'Test'
        azureSubscriptionSPN: $(testAzureSubscriptionSPN)
        location: $(location)
        parameterFile: $(testParameterFile)
        resourceGroupName: $(testResourceGroupName)
        TAGEnvironment: $(testTAGEnvironment)

 