name: OPS-Core-InfrastructureDeployment

parameters:
- name: Environment
  displayName: DeploymentEnvironment
  type: string
  default: 'Dev'
  values:
  - Dev
  - DevTest
  - Test

variables:
  - ${{ if eq(parameters.PipelineEnvironment, 'DevTest') }}:
    - group: vg-odin-devTest-core
  - ${{ if eq(parameters.PipelineEnvironment, 'Test') }}:
    - group: vg-odin-test-core

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DevTestRelease
    condition: and(always(), or(eq('${{ parameters.Environment }}', 'DevTest') , eq('${{ parameters.Environment }}', 'All')) )
    jobs:
    - template: azure-deploy.yml
      parameters:
        Stage: DevTest
        PipelineEnvironment: 'DevTest'
        azureSubscriptionSPN: ${{ variables.azureSubscriptionSPN }}
        location: ${{ variables.location }}
        parameterFile: ${{ variables.parameterFile }}
        resourcePrefix: ${{ variables.resourcePrefix }}
        TAGEnvironment: ${{ variables.TAGEnvironment }}


  - stage: TestRelease
    condition: and(always(), or(eq('${{ parameters.Environment }}', 'Test') , eq('${{ parameters.Environment }}', 'All')) )     
    jobs:
    - template: azure-deploy.yml
      parameters:
        Stage: Test
        PipelineEnvironment: 'Test'
        azureSubscriptionSPN: ${{ variables.azureSubscriptionSPN }}
        location: ${{ variables.location }}
        parameterFile: ${{ variables.parameterFile }}
        resourcePrefix: ${{ variables.resourcePrefix }}
        TAGEnvironment: ${{ variables.TAGEnvironment }}
