name: OPS-Core-InfrastructureDeployment

parameters:
- name: Environment
  displayName: DeploymentEnvironment
  type: string
  default: 'Dev'
  values:
  - Dev
  - DevTest
  - Test

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DevTestRelease
    condition: and(always(), or(eq('${{ parameters.Environment }}', 'DevTest') , eq('${{ parameters.Environment }}', 'All')) )
    jobs:
    - template: azure-deploy.yml
      parameters:
        Stage: Dev
        PipelineEnvironment: 'DevTest'


  - stage: TestRelease
    condition: and(always(), or(eq('${{ parameters.Environment }}', 'Test') , eq('${{ parameters.Environment }}', 'All')) )     
    jobs:
    - template: azure-deploy.yml
      parameters:
        Stage: Test
        PipelineEnvironment: 'Test'
