name: OPS-Core-InfrastructureDeployment

parameters:
- name: Environment
  displayName: Environment
  type: string
  default: 'DevTest'
  values:
  - Dev
  - DevTest
  - Test

variables:
  - group: vg-odin-core

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DevTestRelease
    jobs:
    - template: azure-deploy.yml
      parameters:
        Stage: DevTest
        Environment: 'DevTest'
        #azureSubscriptionSPN: ${{ variables.devTestAzureSubscriptionSPN }}
        azureSubscriptionSPN: $(devTestAzureSubscriptionSPN)
        location: ${{ variables.location }}
        parameterFile: ${{ variables.devTestParameterFile }}
        resourcePrefix: ${{ variables.devTestResourcePrefix }}
        TAGEnvironment: ${{ variables.devTestTAGEnvironment }}


  - stage: TestRelease
    jobs:
    - template: azure-deploy.yml
      parameters:
        Stage: Test
        Environment: 'Test'
        azureSubscriptionSPN: ${{ variables.testAzureSubscriptionSPN }}
        location: ${{ variables.location }}
        parameterFile: ${{ variables.testParameterFile }}
        resourcePrefix: ${{ variables.testResourcePrefix }}
        TAGEnvironment: ${{ variables.testTAGEnvironment }}
